-- AlterTable
ALTER TABLE `CheckIn` MODIFY `type` ENUM('NORMAL', 'SICK_LEAVE', 'PERSONAL_LEAVE', 'NOT_CHECKED_IN', 'ABSENT', 'REQUEST_FOR_CHECK_IN', 'FORGOT_TO_CHECK_IN', 'HOLIDAY', 'CLOSED_FOR_CHECK_IN') NOT NULL DEFAULT 'NOT_CHECKED_IN';

-- AlterTable
ALTER TABLE `Setting` ADD COLUMN `requestEndTime` INTEGER NOT NULL DEFAULT 12,
    ADD COLUMN `requestStartTime` INTEGER NOT NULL DEFAULT 9,
    MODIFY `checkInEndTime` INTEGER NOT NULL DEFAULT 12;
