-- AlterTable
ALTER TABLE `Setting` ADD COLUMN `checkInEndDay` INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN `checkInEndTime` INTEGER NOT NULL DEFAULT 9,
    ADD COLUMN `checkInStartDay` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `checkInStartTime` INTEGER NOT NULL DEFAULT 7;
